export default [
  { id: 1, src: "./img/8-bit_card.png", webp:'./img/8-bit_card.webp', color: "black", description: '8-bit' },
  { id: 2, src: "./img/Bibi_card.png", webp:'./img/Bibi_card.webp', color: "green", description: 'Bibi' },
  { id: 3, src: "./img/Bull_card.png", webp:'./img/Bull_card.webp', color: "yellow", description: 'Bull' },
  { id: 4, src: "./img/Byron_card.png", webp:'./img/Byron_card.webp', color: "grey", description: 'Byron' },
  { id: 5, src: "./img/Carl_card.png", webp:'./img/Carl_card.webp', color: "red", description: 'Carl' },
  { id: 6, src: "./img/Colt_card.png", webp: './img/Colt_card.webp', color: "gold", description: "Colt" },
  { id: 7, src: "./img/Crow_card.png", webp:'./img/Crow_card.webp', color: "blue", description: "Crow" },
  { id: 8, src: "./img/Edgar_card.png", webp:'./img/Edgar_card.webp', color: "teal", description: 'Edgar' },
  { id: 9, src: "./img/Elprimo_card.png", webp:'./img/Elprimo_card.webp', color: "orange", description: "Elprimo" },
  { id: 10, src: "./img/Frank_card.png", webp:'./img/Frank_card.webp', color: "aqua", description: 'Frank' },
  { id: 11, src: "./img/Leon_card.png", webp:'./img/Leon_card.webp', color: "purple", description: 'Leon' },
  { id: 12, src: "./img/Mortis_card.png", webp:'./img/Mortis_card.webp', color: "pink", description: 'Mortis' },
  { id: 13, src: "./img/Nani_card.png", webp:'./img/Nani_card.webp', color: "brown", description: 'Nani'},
  { id: 14, src: "./img/Nita_card.png", webp:'./img/Nita_card.webp', color: "darkcyan", description: 'Nita' },
  { id: 15, src: "./img/Pam_card.png", webp:'./img/Pam_card.webp', color: "indigo", description: "Pam" },
  { id: 16, src: "./img/Poko_card.png", webp:'./img/Poko_card.webp', color: "coral", description: "Poko" },
  { id: 17, src: "./img/Riko_card.png", webp:'./img/Riko_card.webp', color: "navy", description: "Riko" },
  { id: 18, src: "./img/Sandy_card.png", webp:'./img/Sandy_card.webp', color: "lime", description: 'Sandy' },
  { id: 19, src: "./img/Shelly_card.png", webp:'./img/Shelly_card.webp', color: "olive", description: 'Shelly' },
  { id: 20, src: "./img/Spike_card.png", webp:'./img/Spike_card.webp', color: "tan", description: 'Spike' },
  { id: 21, src: "./img/Tara_card.png", webp:'./img/Tara_card.webp', color: "tan", description: 'Tara' },
  { id: 22, src: "./img/Volt_card.png", webp:'./img/Volt_card.webp', color: "tan", description: 'Volt' },
];