export const enLanguage = {
   subtitleGame: "cards",
   subtitleAuthors: "by hope team",
   buttonTitle: "play",
   howToPlayModalTitle: "How To Play?",
   howToPlayModalText: `First, click the "play" button. You will see a table where you need to select the
    number of cards and time. If you are not playing alone, go to the next "multiplayer" function, it is next to
    the "single player" function. You need to choose the number of cards and the number of players. Then click
    "start". You see the cards on the screen. You must find two identical cards for the time you have chosen.`,
   authorsModalTitle: "authors of this game",
   authorsMaxTitle: "Max Popsuy",
   authorsMaxText: "12 years old. Live in Kiev.",
   authorsMariaTitle: "Maria Hrypych",
   authorsMariaText: "HR manager",
   authorsDmytroTitle: "Kolisnyk Dmytro",
   authorsDmytroText: "TeamLead. 16 years old.",
   authorsIgorTitle: "Ihor Yakibiuk",
   authorsIgorText: "Man who study Front_End development.",
   authorsFooterText: "2021 HOPE Team © all rights reserved",
   settingsModalTitle: "Settings",
   settingsModalSubtitleSound: "Sound",
   settingsModalSubtitleLanguage: "Language",
   settingsModalSubtitleBackground: "Background",
   startGameModalSinglePlayerSubtitle: "Single player",
   startGameModalMultiPlayerSubtitle: "Multi player",
   startGameModalArcadeSubtitle: "Arcade",
   startGameModalAmountOfCardsSubtitle: "Select the amount of cards",
   startGameModalAmountOfTimeSubtitle: "Select the amount of time",
   buttonTitleTime05: "0.5 min",
   buttonTitleTime1: "1 min",
   buttonTitleTime2: "2 min",
   buttonTitleTime3: "3 min",
   multiPlayerAmountOfPlayers: "Select the number of players",
   arcadeLevelSelect: "Select level",
   buttonStartTitle: "start",
   modalPausedTitle: "Game paused!",
   modalButtonResumeTitle: "Resume",
   modalButtonBackToMenuTitle: "Back to menu",
   modalButtonSettingsTitle: "Settings",
   modalButtonHowToPlayTitle: "How to play",
   wordBeforeGame: "GO!",
   winModalTitle: "You WON!",
   buttonBackToMenu: "Back to menu",
   buttonReplayTitle: "Replay",
   winModalArcade: "You complete stage 1",
   winModalArcadeButtonMenuTitle: "menu",
   winModalArcadeButtonNextLevelTitle: "Next level",
   lostModalTitle: "You LOST",
   lastWinArcadeModal: "You Completed this game!",
};

export const uaLanguage = {
   subtitleGame: "картки",
   subtitleAuthors: "команда HOPE",
   buttonTitle: "грати",
   howToPlayModalTitle: "Як Грати?",
   howToPlayModalText: `Спочатку натисніть кнопку «грати». Ви побачите таблицю, де вам потрібно вибрати
    кількість карток і час. Якщо ви граєте не на самоті, перейдіть до наступної "багатокористувацької" функції, яка знаходиться поруч
    функції "для одного гравця". Вам потрібно вибрати кількість карт і кількість гравців. Потім клацніть
    "почати". Ви бачите картки на екрані. Ви повинні знайти дві однакові картки впродовж обраного вами часу.`,
   authorsModalTitle: "автори цієї гри",
   authorsMaxTitle: "Макс Попсуй",
   authorsMaxText: "12 років. Живу у Києві",
   authorsMariaTitle: "Марія Грипич",
   authorsMariaText: "HR менеджер",
   authorsDmytroTitle: "Колісник Дмитро",
   authorsDmytroText: "Лідер команди. 16 років.",
   authorsIgorTitle: "Ігор Якіб'юк",
   authorsIgorText: "Людина, яка вчить Front_End розробку.",
   authorsFooterText: "2021 HOPE Команда © всі права захищені",
   settingsModalTitle: "Налаштування",
   settingsModalSubtitleSound: "Звук",
   settingsModalSubtitleLanguage: "Мова",
   settingsModalSubtitleBackground: "Фон",
   startGameModalSinglePlayerSubtitle: "Одиночна гра",
   startGameModalMultiPlayerSubtitle: "Командна гра",
   startGameModalArcadeSubtitle: "Аркада",
   startGameModalAmountOfCardsSubtitle: "Виберіть кількість карток",
   startGameModalAmountOfTimeSubtitle: "виберіть час",
   buttonTitleTime05: "0.5 хв",
   buttonTitleTime1: "1 хв",
   buttonTitleTime2: "2 хв",
   buttonTitleTime3: "3 хв",
   multiPlayerAmountOfPlayers: "Виберіть кількість гравців",
   arcadeLevelSelect: "Виберіть рівень",
   buttonStartTitle: "почати",
   modalPausedTitle: "Гра призупинена!",
   modalButtonResumeTitle: "Продовжити",
   modalButtonBackToMenuTitle: "Повернутись до меню",
   modalButtonSettingsTitle: "Налаштування",
   modalButtonHowToPlayTitle: "Як грати",
   wordBeforeGame: "ПОЇХАЛИ!",
   winModalTitle: "Ви ПЕРЕМОГЛИ!",
   buttonBackToMenu: "Повернутись до меню",
   buttonReplayTitle: "Спробувати ще раз",
   winModalArcade: "Ви пройшли 1 рівень",
   winModalArcadeButtonMenuTitle: "меню",
   winModalArcadeButtonNextLevelTitle: "Наступний рівень",
   lostModalTitle: "Ви ПРОГРАЛИ",
   lastWinArcadeModal: "Ви закінчили цю гру!",
};

export const plLanguage = {
   subtitleGame: "karty",
   subtitleAuthors: "zrobić przez zespół hope",
   buttonTitle: "grać",
   howToPlayModalTitle: "Jak grać?",
   howToPlayModalText: `Najpierw kliknij przycisk „odtwórz”. Zobaczysz tabelę, w której musisz wybrać
    liczba kart i czas. Jeśli nie grasz sam, przejdź do następnej funkcji „Tryb wieloosobowy”, która znajduje się obok
    funkcja „Jeden gracz”. Musisz wybrać liczbę kart i liczbę graczy. Następnie kliknij
    "początek". Widzisz karty na ekranie. Musisz znaleźć dwie identyczne karty na wybrany czas.`,
   authorsModalTitle: "autorzy tej gry.",
   authorsMaxTitle: "Max Popsuy",
   authorsMaxText: "12 lat. Mieszkaj w Kijowie.",
   authorsMariaTitle: "Maria Hrypych",
   authorsMariaText: "HR menedżer",
   authorsDmytroTitle: "Kolisnyk Dmytro",
   authorsDmytroText: "TeamLead. 16 lat.",
   authorsIgorTitle: "Ihor Yakibiuk",
   authorsIgorText: "Człowiek, który studiuje rozwój front-endu.",
   authorsFooterText: "2021 HOPE Zespół © Wszelkie prawa zastrzeżone",
   settingsModalTitle: "Ustawienia",
   settingsModalSubtitleSound: "Dźwięk",
   settingsModalSubtitleLanguage: "Język",
   settingsModalSubtitleBackground: "tło",
   startGameModalSinglePlayerSubtitle: "Jeden gracz",
   startGameModalMultiPlayerSubtitle: "Tryb wieloosobowy",
   startGameModalArcadeSubtitle: "Arkada",
   startGameModalAmountOfCardsSubtitle: "Wybierz ilość kart",
   startGameModalAmountOfTimeSubtitle: "Wybierz ilość czasu",
   buttonTitleTime05: "0.5 min",
   buttonTitleTime1: "1 min",
   buttonTitleTime2: "2 min",
   buttonTitleTime3: "3 min",
   multiPlayerAmountOfPlayers: "Wybierz liczbę graczy",
   arcadeLevelSelect: "Wybierz poziom",
   buttonStartTitle: "początek",
   modalPausedTitle: "Gra wstrzymana!",
   modalButtonResumeTitle: "Wznawianie",
   modalButtonBackToMenuTitle: "Powrót do menu",
   modalButtonSettingsTitle: "Ustawienia",
   modalButtonHowToPlayTitle: "Jak grać",
   wordBeforeGame: "POJECHALIŚMY!",
   winModalTitle: "You WON!",
   buttonBackToMenu: "Powrót do menu",
   buttonReplayTitle: "Powtórna rozgrywka",
   winModalArcade: "Ukończyłeś etap 1",
   winModalArcadeButtonMenuTitle: "menu",
   winModalArcadeButtonNextLevelTitle: "Następny poziom",
   lostModalTitle: "Przegrałeś",
   lastWinArcadeModal: "Ukończyłeś tę grę!",
};

export const deLanguage = {
   subtitleGame: "Karten",
   subtitleAuthors: "von Hope-Team",
   buttonTitle: "spielen",
   howToPlayModalTitle: "Spielanleitung?",
   howToPlayModalText: `Klicken Sie zunächst auf die Schaltfläche "Play". Sie sehen eine Tabelle, in der Sie die auswählen müssen select
    Anzahl der Karten und Zeit. Wenn Sie nicht alleine spielen, gehen Sie zur nächsten "Multiplayer"-Funktion, sie befindet sich neben
    die "Einzelspieler"-Funktion. Sie müssen die Anzahl der Karten und die Anzahl der Spieler auswählen. Dann klick
    "Start". Sie sehen die Karten auf dem Bildschirm. Sie müssen zwei identische Karten für die von Ihnen gewählte Zeit finden.`,
   authorsModalTitle: "Autoren dieses Spiels",
   authorsMaxTitle: "Max Popsuy",
   authorsMaxText: "12 Jahre alt. Lebe in Kiew.",
   authorsMariaTitle: "Maria Hrypych",
   authorsMariaText: "HR manager",
   authorsDmytroTitle: "Kolisnyk Dmytro",
   authorsDmytroText: "Teamleiter. 16 Jahre alt.",
   authorsIgorTitle: "Ihor Yakibiuk",
   authorsIgorText: "Mann, der Front-End-Entwicklung studiert.",
   authorsFooterText: "2021 HOPE Team © Alle Rechte vorbehalten",
   settingsModalTitle: "die Einstellungen",
   settingsModalSubtitleSound: "Klang",
   settingsModalSubtitleLanguage: "Sprache",
   settingsModalSubtitleBackground: "Hintergrund",
   startGameModalSinglePlayerSubtitle: "Einzelspieler",
   startGameModalMultiPlayerSubtitle: "Mehrspieler",
   startGameModalArcadeSubtitle: "Arkade",
   startGameModalAmountOfCardsSubtitle: "Wählen Sie die Anzahl der Karten aus",
   startGameModalAmountOfTimeSubtitle: "Wählen Sie die Dauer",
   buttonTitleTime05: "0.5 Mindest",
   buttonTitleTime1: "1 Mindest",
   buttonTitleTime2: "2 Mindest",
   buttonTitleTime3: "3 Mindest",
   multiPlayerAmountOfPlayers: "Wählen Sie die Anzahl der Spieler",
   arcadeLevelSelect: "Stufe auswählen",
   buttonStartTitle: "start",
   modalPausedTitle: "Spiel pausiert!",
   modalButtonResumeTitle: "Fortsetzen",
   modalButtonBackToMenuTitle: "Zurück zum Menü",
   modalButtonSettingsTitle: "die Einstellungen",
   modalButtonHowToPlayTitle: "Spielanleitung",
   wordBeforeGame: "GEHEN!",
   winModalTitle: "Du hast gewonnen!",
   buttonBackToMenu: "Zurück zum Menü",
   buttonReplayTitle: "Wiederholung",
   winModalArcade: "Sie beenden Stufe 1",
   winModalArcadeButtonMenuTitle: "Speisekarte",
   winModalArcadeButtonNextLevelTitle: "Nächste Stufe",
   lostModalTitle: "Du hast verloren",
   lastWinArcadeModal: "Du hast dieses Spiel abgeschlossen!",
};

export const jpLanguage = {
   subtitleGame: "カード",
   subtitleAuthors: "『希望』チームが作った",
   buttonTitle: "演奏する",
   howToPlayModalTitle: "遊び方",
   howToPlayModalText: `最初に「再生」ボタンを押って、を選択する必要がある表が表示されます
    カードの数と時間。 一人でプレイしていない場合は、次の「マルチプレイヤー」機能に移動します。
    「シングルプレイヤー」機能。 カードの数とプレイヤーの数を選択する必要があります。次に、をクリックします
    "開始"。 画面にカードが表示されます。あなたはあなたが選んだ時間のために2枚の同じカードを見つけなければなりません。`,
   authorsModalTitle: "このゲームの作者",
   authorsMaxTitle: "Max Popsuy",
   authorsMaxText: "12歳。 キエフに住んでいます。",
   authorsMariaTitle: "Maria Hrypych",
   authorsMariaText: "人事マネージャー",
   authorsDmytroTitle: "Kolisnyk Dmytro",
   authorsDmytroText: "チームリーダー。 16歳。",
   authorsIgorTitle: "Ihor Yakibiuk",
   authorsIgorText: "フロントエンド開発を研究する男。",
   authorsFooterText: "2021 HOPE Team © 全著作権所有",
   settingsModalTitle: "設定",
   settingsModalSubtitleSound: "音",
   settingsModalSubtitleLanguage: "言語",
   settingsModalSubtitleBackground: "バックグラウンド",
   startGameModalSinglePlayerSubtitle: "シングルプレーヤー",
   startGameModalMultiPlayerSubtitle: "マルチプレイヤー",
   startGameModalArcadeSubtitle: "アーケード",
   startGameModalAmountOfCardsSubtitle: "カードの数を選択します",
   startGameModalAmountOfTimeSubtitle: "時間の長さを選択してください",
   buttonTitleTime05: "0.5 分",
   buttonTitleTime1: "1 分",
   buttonTitleTime2: "2 分",
   buttonTitleTime3: "3 分",
   multiPlayerAmountOfPlayers: "プレーヤーの数を選択します",
   arcadeLevelSelect: "レベルを選択",
   buttonStartTitle: "開始",
   modalPausedTitle: "ゲームが一時停止しました！",
   modalButtonResumeTitle: "履歴書",
   modalButtonBackToMenuTitle: "メニューに戻る",
   modalButtonSettingsTitle: "設定",
   modalButtonHowToPlayTitle: "遊び方",
   wordBeforeGame: "GO!",
   winModalTitle: "あなたが勝った！",
   buttonBackToMenu: "メニューに戻る",
   buttonReplayTitle: "やり直す",
   winModalArcade: "ステージ1を完了します",
   winModalArcadeButtonMenuTitle: "メニュー",
   winModalArcadeButtonNextLevelTitle: "次のレベル",
   lostModalTitle: "あなたが負けた",
   lastWinArcadeModal: "このゲームを完了しました！",
};